In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [6]:
data=pd.read_csv('Admission_Predict.csv')

In [7]:
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

# **Training and Testing the model**

In [8]:
x=data.drop(['Chance of Admit '],axis=1) 
y=data['Chance of Admit ']

In [9]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [10]:
x_train

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
101,102,312,105,2,2.5,3.0,8.12,0
310,311,320,104,3,3.0,3.5,8.74,1
388,389,296,97,2,1.5,2.0,7.80,0
41,42,316,105,2,2.5,2.5,8.20,1
50,51,313,98,3,2.5,4.5,8.30,1
...,...,...,...,...,...,...,...,...
334,335,312,107,4,4.5,4.0,8.65,1
274,275,315,100,1,2.0,2.5,7.95,0
167,168,313,102,3,2.0,3.0,8.27,0
179,180,307,102,3,3.0,3.0,8.27,0
182,183,299,100,2,3.0,3.5,7.88,0

In [11]:
y_train

101    0.64
310    0.76
388    0.49
41     0.49
50     0.76
       ...
334    0.73
274    0.58
167    0.64
179    0.73
182    0.68
Name: Chance of Admit , Length: 340, dtype: float64

In [12]:
x_test

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
30,31,300,97,2,3.0,3.0,8.10,1
150,151,334,114,4,4.0,4.0,9.43,1
132,133,309,105,5,3.5,3.5,8.56,0
270,271,306,105,2,2.5,3.0,8.22,1
55,56,320,103,3,3.0,3.0,7.70,0
14,15,311,104,3,3.5,2.0,8.20,1
25,26,340,120,5,4.5,4.5,9.60,1
268,269,327,113,4,4.5,5.0,9.14,0
131,132,303,105,5,5.0,4.5,8.65,0
171,172,334,117,5,4.0,4.5,9.07,1
328,329,324,112,4,4.0,3.5,8.77,1
164,165,329,111,4,4.5,4.0,9.01,1
305,306,321,109,3,3.5,3.5,8.80,1
180,181,300,104,3,3.5,3.0,8.16,0
324,325,315,104,3,3.0,2.5,8.33,0
185,186,327,113,4,4.5,4.5,9.11,1
360,361,322,110,3,4.0,5.0,8.64,1
243,244,325,114,3,3.5,3.0,9.04,1
188,189,331,115,5,4.5,3.5,9.36,1
48,49,321,110,3,3.5,5.0,8.85,1
365,366,330,114,4,4.5,3.0,9.17,1
163,164,317,105,3,3.5,3.0,8.56,0
95,96,304,100,4,1.5,2.5,7.84,0
288,289,314,104,4,5.0,5.0,9.02,0
72,73,321,111,5,5.0,5.0,9.45,1
197,198,310,106,2,3.5,2.5,8.33,0
53,54,324,112,4,4.0,2.5,8.10,1
299,300,305,112,3,3.0,3.5,8.65,0
293,294,312,98,1,3.5,3.0,8.18,1
168,169,293,97,2,2.0,4.0,7.80,1
318,319,324,111,3,2.5,2.0,8.80,1
392,393,326,112,4,4.0,3.5,9.12,1
336,337,319,110,3,3.0,2.5,8.79,0
18,19,318,110,3,4.0,3.0,8.80,0
113,114,320,110,2,4.0,3.5,8.56,0
257,258,324,100,3,4.0,5.0,8.64,1
84,85,340,115,5,4.5,4.5,9.45,1
193,194,336,118,5,4.5,5.0,9.53,1
251,252,316,99,2,2.5,3.0,9.00,0
244,245,314,107,2,2.5,4.0,8.56,0
4,5,314,103,2,2.0,3.0,8.21,0
377,378,290,100,1,1.5,2.0,7.56,0
92,93,298,98,2,4.0,3.0,8.03,0
89,90,316,109,4,4.5,3.5,8.76,1
20,21,312,107,3,3.0,2.0,7.90,1
235,236,326,111,5,4.5,4.0,9.23,1
345,346,316,98,1,1.5,2.0,7.43,0
6,7,321,109,3,3.0,4.0,8.20,1
265,266,313,102,3,2.5,2.5,8.68,0
124,125,301,106,4,2.5,3.0,8.47,0
387,388,307,105,2,2.0,3.5,8.10,0
380,381,322,104,3,3.5,4.0,8.84,1
221,222,316,110,3,3.5,4.0,8.56,0
174,175,321,111,4,4.0,4.0,8.97,1
83,84,322,115,5,4.0,4.5,9.36,1
202,203,340,120,5,4.5,4.5,9.91,1
111,112,321,109,4,4.0,4.0,8.68,1
178,179,309,108,3,2.5,3.0,8.12,0
309,310,308,110,4,3.5,3.0,8.60,0
137,138,316,100,2,1.5,3.0,8.16,1

In [13]:
y_test

30     0.65
150    0.93
132    0.71
270    0.72
55     0.64
14     0.61
25     0.94
268    0.83
131    0.77
171    0.89
328    0.80
164    0.81
305    0.74
180    0.71
324    0.67
185    0.89
360    0.85
243    0.76
188    0.93
48     0.82
365    0.86
163    0.68
95     0.42
288    0.82
72     0.93
197    0.73
53     0.72
299    0.71
293    0.64
168    0.64
318    0.79
392    0.84
336    0.72
18     0.63
113    0.72
257    0.78
84     0.94
193    0.94
251    0.70
244    0.63
4      0.65
377    0.47
92     0.34
89     0.74
20     0.64
235    0.88
345    0.49
6      0.75
265    0.71
124    0.57
387    0.53
380    0.78
221    0.75
174    0.87
83     0.92
202    0.97
111    0.69
178    0.72
309    0.70
137    0.71
Name: Chance of Admit , dtype: float64

# **Model Evaluation**

In [14]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [15]:
model.score(x_test,y_test)

0.852449199309218

In [16]:
y_predict=model.predict(x_test)

In [17]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
import numpy as np
print('Mean Absolute Error:', mean_absolute_error(y_test, y_predict))  
print('Mean Squared Error:', mean_squared_error(y_test, y_predict))  
print('Root Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_predict)))

Mean Absolute Error: 0.03507595764451041
Mean Squared Error: 0.002599595091537074
Root Mean Squared Error: 0.05098622452719042

In [18]:
y_train = (y_train>0.5)
y_test = (y_test>0.5)

In [19]:
from sklearn.linear_model._logistic import LogisticRegression

lore = LogisticRegression(random_state=0, max_iter=1000)

lr = lore.fit(x_train, y_train)

In [20]:
y_pred = lr.predict(x_test)

In [21]:
y_pred

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])